repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: LICENSES/headers
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml

  - repo: https://github.com/PyCQA/isort
    rev: 7.0.0
    hooks:
      - id: isort
  - repo: https://github.com/pylint-dev/pylint
    rev: "v4.0.4"
    hooks:
    - id: pylint
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.19.1'
    hooks:
    -   id: mypy
#  - repo: https://github.com/myint/docformatter
#    rev: v1.7.7
#    hooks:
#      - id: docformatter
#        # it doesn't seem to pick up the config correctly
#        args: [
#          --in-place,
#          --black,
#          --config,
#          ./pyproject.toml
#        ]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
